version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: testtrack-db
    restart: always
    environment:
      POSTGRES_USER: testtrack
      POSTGRES_PASSWORD: testtrack
      POSTGRES_DB: testtrack
    ports:
      - "5432:5432"

  backend:
    build: ./apps/api/backend
    ports:
      - "5000:5000"

  frontend:
    build: ./apps/web/frontend
    ports:
      - "3000:3000"