name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd apps/api/backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd apps/web/frontend
          npm install

      - name: Build Frontend
        run: |
          cd apps/web/frontend
          npm run build

      - name: Production Deploy Message
        run: echo "Deploying to production..."